config/routes.rb
Rails.application.routes.draw do
  resources  :authentications, only: %i[create destroy]
  get '/auth/:provider/callback' => 'authentications#create'

  devise_for :users, controllers: {
    registrations: 'registrations',
    sessions: 'sessions',
    passwords: 'passwords'
  }

  resources :activities do
    resource :participation, only: %i[create destroy]
  end
  root to: 'activities#index'
end

app/models/activity.rb
class Activity < ApplicationRecord
  DEFAULT_LIMIT = 100

  attr_accessor :event
  attr_writer :participation_source # DI
  serialize :additional_information, JSON

  belongs_to :creator, class_name: 'User'
  has_many :participations, dependent: :destroy
  has_many :participants, through: :participations, class_name: 'User'

  validates :start_time, presence: true, allow_blank: false, if: -> { !anytime? }
  validates :end_time, presence: true, allow_blank: false, if: -> { !anytime? }
  validates :anytime, presence: true, allow_blank: false, allow_nil: false, if: -> { start_time.blank? && end_time.blank? }
  validates :name, presence: true, allow_blank: false
  validates :location, presence: true, allow_blank: false
  validates :limit_of_participants, numericality: { greater_than: 0 }, allow_nil: true
  validate  :time_frame_order, if: -> { !anytime && event && start_time.present? && end_time.present? }
  validate  :during_the_event, if: -> { !anytime && event && start_time.present? && end_time.present? }
  validates :event, presence: true
  validate  :image_url_valid, if: -> { image_url.present? }

  before_validation :clear_time_frame, if: -> { anytime }

  class << self
    def recent(limit = DEFAULT_LIMIT)
      find_recent(limit)
    end

    def all_activities(limit = DEFAULT_LIMIT)
      find_all(limit)
    end

    def today
      find_today
    end

    def with_name_like(name)
      find_with_name_like(name)
    end

    def created_by(user)
      find_created_by(user)
    end

    def participated_by(user)
      find_participated_by(user)
    end

    def order_by_start_time
      t = Time.zone.now.beginning_of_day
      custom_order = <<~SQL
        *,
        (
          CASE
            WHEN end_time <= '#{t}' THEN 10
            WHEN anytime=true THEN 2
            ELSE 1
          END
        ) as CUSTOM_ORDER
SQL
      select(custom_order).order('CUSTOM_ORDER ASC, start_time ASC, name ASC')
    end

    private

    def find_all(limit)
      limit(limit).order_by_start_time
    end

    def find_recent(limit)
      where('start_time >= :t OR anytime = true', t: 1.month.ago)
        .limit(limit)
        .order_by_start_time
    end

    def find_today
      where('(NOT(start_time <= :t1 AND end_time = :t1 ) AND (start_time <= :t2 AND end_time >= :t1)) OR anytime=true',
            t1: Time.zone.now.beginning_of_day,
            t2: Time.zone.now.end_of_day).order_by_start_time
    end

    def find_with_name_like(name)
      where('name ILIKE :q', q: "%#{name}%").order_by_start_time
    end

    def find_created_by(user)
      where(creator_id: user).order_by_start_time
    end

    def find_participated_by(user)
      joins(:participations).where(participations: { user_id: user }).order_by_start_time
    end
  end

  def full_by
    limit_of_participants.nil? ? 0 : [100.0 * participations_count / limit_of_participants.to_f, 100.0].min
  end

  def anybody_can_join?
    limit_of_participants.nil?
  end

  def today?
    return true if anytime?
    t1 = Time.zone.now.beginning_of_day
    t2 = Time.zone.now.end_of_day
    if start_time <= t1 && end_time == t1
      false
    else
      start_time <= t2 && end_time >= t1
    end
  end

  def upcoming?
    start_time > Time.zone.now.end_of_day
  end

  def in_past?
    return false if anytime?
    end_time < Time.zone.now.beginning_of_day
  end

  def full?
    participations_count >= limit_of_participants
  rescue StandardError
    false
  end

  def new_participation(user)
    participation_source.().tap do |participation|
      participation.activity = self
      participation.participant = user
    end
  end

  def participation(user)
    participations.find_by(user_id: user)
  end

  def dates
    (start_time.to_date..end_time.to_date).to_a
  end

  private

  def participation_source
    @participation_source ||= Participation.public_method(:new)
  end

  def clear_time_frame
    self.start_time = nil
    self.end_time = nil
  end

  def time_frame_order
    errors.add(:end_time, I18n.t('activities.errors.end_time.before_start')) if end_time < start_time
  end

  def during_the_event
    errors.add(:start_time, I18n.t('activities.errors.end_time.too_early')) if start_time < event.start_time
    errors.add(:end_time, I18n.t('activities.errors.end_time.too_late')) if end_time > event.end_time
  end

  def image_url_valid
    errors.add(:image_url, I18n.t('activities.errors.image_url.protocol_not_supported')) unless URI.parse(image_url).is_a?(URI::HTTP)
  rescue URI::InvalidURIError
    errors.add(:image_url, I18n.t('activities.errors.image_url.invalid'))
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  respond_to :html

  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :load_and_authorize_activity, only: %i[show edit update destroy]

  def index
    @activities_per_day = current_event.activities_per_day(current_user, query_params[:search], query_params[:filter])
    @counters = current_event.counters(current_user)
    respond_with(@activities_per_day)
  end

  def show
    respond_with(@activity)
  end

  def new
    @activity = current_event.new_activity(current_user, {})
    authorize @activity
    respond_with(@activity)
  end

  def edit
    respond_with(@activity)
  end

  def create
    @activity = current_event.new_activity(current_user, sanitized_params)
    authorize @activity
    @activity.save
    respond_with(@activity, location: activities_path)
  end

  def update
    @activity.update(sanitized_params)
    respond_with(@activity, location: edit_activity_path(@activity))
  end

  def destroy
    if params[:confirm_delete]
      @activity.destroy
    else
      @activity.errors.add(:base, :invalid)
    end
    respond_with(@activity, location: root_path, action: :edit)
  end

  private

  def load_and_authorize_activity
    @activity = current_event.activity(params[:id]) or
      raise(ActiveRecord::RecordNotFound)
    authorize @activity
    @activity = @activity.decorate
  end

  def sanitized_params
    params.require(:activity)
          .permit(:start_time,
                  :end_time,
                  :name,
                  :location,
                  :requirements,
                  :requires_event_ticket,
                  :description,
                  :limit_of_participants,
                  :anytime,
                  :image_url)
  end

  def query_params
    params.permit(:search, :filter)
  end
end

app/views/activities/_action.html.haml
- remote = defined?(remote) ? remote : true
.action{ class: type }
  - case type
  - when 'owner'
    = link_to edit_activity_path(activity), title: t('activities.edit.title') do
      %span
      = t('activities.edit.label')
  - when 'participant'
    - unless activity.in_past? || activity.official
      = button_to activity_participation_path(activity), method: :delete, remote: remote, title: t('activities.leave.title') do
        %span
        = t('activities.leave.label')
  - else
    - unless activity.full? || activity.in_past? || activity.official
      = button_to activity_participation_path(activity), method: :post, remote: remote, title: t('activities.join.title') do
        %span
        = t('activities.join.label')

app/views/activities/_activity.html.haml
- type = activity.relation_ship_with(current_user)

%li{ id: "activity-#{activity.id}", class: activity.css_classes }
  .container

    = render 'activities/progress', activity: activity

    .labels
      %h4
        = activity.name
      %p.creator
        = activity.creator_name
      - if activity.requires_event_ticket
        = image_tag 'shared/IoR_illustration.svg',
          class: 'requires_event_ticket',
          alt: t('activities.requires_event_ticket'),
          title: t('activities.requires_event_ticket')
      %p.time
        = activity.formatted_time

    = render 'activities/action', activity: activity, type: type, remote: true

    %a.details{ href: activity_path(activity), title: activity.name }
      %span
        = t('activities.more_info.label')
    - unless type == 'default'
      %span.icon

app/views/activities/_activity_day.html.haml
.activity-day
  %h1= I18n.l(day.in_time_zone, format: :nice_date)
  = render ActivityDecorator.decorate_collection(activities)

app/views/activities/_delete_form.html.haml
= form_tag activity_path(activity), method: :delete do

  %fieldset
    %label.inline
      = check_box_tag :confirm_delete
      = t('delete_activity_form.confirmation', count: activity.participants.count)

  = button_tag t('delete_activity_form.submit')

app/views/activities/_form.html.haml
= form_for activity, html: { id: 'new-activity' } do |f|

  %label.name
    = f.text_field :name, placeholder: t('activity_form.name.label'), class: 'title'

  %hr

  - fancy_datime_select f, :start_time, activity
  %span.divider> &ndash;
  - fancy_datime_select f, :end_time, activity

  %fieldset.anytime
    %span.between
      = t('common.or').downcase
    %label.inline
      = f.check_box :anytime
      = t('activity_form.anytime.hint')

  %hr

  %label.location>
    = f.text_field :location, placeholder: t('activity_form.location.label')
    %small
      = t('activity_form.location.hint')
      %a#show-map= t('activity_form.location.show-map')

  %label.limit-of-participants>
    = f.number_field :limit_of_participants, placeholder: 10, min: 1
    %small
      = t('activity_form.limit_of_participants.hint')

  = image_tag 'activities/meeting_points.svg', class: 'meeting-point-map', id: 'meeting-point-map'

  %label.requirements
    = f.text_area :requirements, placeholder: t('activity_form.requirements.label'), rows: 6, class: 'markdown', title: t('activity_form.markdown_hint')
    %small
      = t('activity_form.requirements.hint')

  %fieldset.requires_event_ticket
    %label.inline
      = f.check_box :requires_event_ticket
      = t('activity_form.requires_event_ticket.hint')

  %label.description
    = f.text_area :description, placeholder: t('activity_form.description.label'), rows: 8, class: 'markdown', title: t('activity_form.markdown_hint')
    %small
      = t('activity_form.description.hint')

  %label.image-url
    = f.url_field :image_url, placeholder: t('activity_form.image_url.label')
    .preview
    %small
      = t('activity_form.image_url.hint')

  %button{ type: 'submit' }>
    %span>
    = t("common.submit.#{activity.new_record? ? 'new' : 'edit'}")

app/views/activities/_progress.html.haml
-# haml-lint:disable InlineStyles

.progress{ data: { progress: activity.full_by }, style: ("background-image: url(#{activity.image_url})" if activity.image_url.present?) }

-# haml-lint:enable InlineStyles

app/views/activities/edit.html.haml
%article
  %header
    %h2
      = t('edit_activity.title')

    %p.meta
      = link_to t('activities.more_info.label_long'), @activity
      %strong.divider
        = t('common.or').downcase
      = link_to t('activities.new.label').downcase, new_activity_path

  = render 'form', activity: @activity


%article.delete-activity
  %header
    %h2= t('activities.danger_zone')
    %p.meta
      %strong= t('delete_activity_form.title')

  = render 'delete_form', activity: @activity

app/views/activities/index.html.haml
%form.filters{ action: activities_path, method: 'GET', id: 'activities-filter' }
  %label>
    = radio_button_tag 'filter', 'today', params[:filter] == 'today', class: 'radio'
    = t('activities.filters.today')
    %strong
      = @counters[:today]
  %label.all.selected>
    = radio_button_tag 'filter', 'all', params[:filter] == 'all' || params[:filter].nil?, class: 'radio'
    = t('activities.filters.all')
    %strong
      = @counters[:all]
  %label.participant>
    = radio_button_tag 'filter', 'participant', params[:filter] == 'participant', class: 'radio'
    = t('activities.filters.participant')
    %strong
      = @counters[:participant]
  %label.owner>
    = radio_button_tag 'filter', 'owner', params[:filter] == 'owner', class: 'radio'
    = t('activities.filters.owner')
    %strong
      = @counters[:owner]
  %label.search
    %input{ type: 'text', name: 'search', placeholder: t('activities.search.placeholder'), value: params[:search] }
  %button{ type: 'submit' }
    = t('activities.filters.submit')

%a#new-activity{ href: new_activity_path, title: t('activities.new.title') }
  %span
  = t('activities.new.label')

%ul#activities
  - @activities_per_day.each do |day, activities|
    = render 'activity_day', day: day, activities: activities

app/views/activities/new.html.haml
%article
  %header
    %h2
      = t('new_activity.title')

  = render 'form', activity: @activity

app/views/activities/show.html.haml
%article#activity
  %header
    %h2
      = @activity.name
      - if @activity.requires_event_ticket
        %br
        = image_tag 'shared/IoR_illustration.svg',
          class: 'requires_event_ticket',
          alt: t('activities.requires_event_ticket'),
          title: t('activities.requires_event_ticket')
    %p.meta
      = t('activities.organized_by_html', name: @activity.creator_name)

    = render 'action', activity: @activity, type: @activity.relation_ship_with(current_user), remote: false

  %section.overview
    = render 'activities/progress', activity: @activity
    %p
      = @activity.room_left
    - if @activity.participants.any?
      .participants
        %h3
          = t('activities.participants')
        %ul
          - ParticipantDecorator.decorate_collection(@activity.participants).each do |participant|
            %li{ title: participant.name }>
              = image_tag(participant.avatar_url(48))

  %section.description
    .wrapper
      = @activity.description_markdown

      - unless @activity.requirements_markdown.empty?
        %h4
          = t('activities.required')
        = @activity.requirements_markdown

  %section.details
    %dl.wrapper
      - if @activity.anytime?
        %dt
          = t('activities.time_and_date')
        %dd
          = t('activities.anytime')
      - else
        %dt
          = t('activities.start.label_short')
        %dd
          = l(@activity.start_time, format: :nice_date_and_time)
        %dt
          = t('activities.end.label_short')
        %dd
          = l(@activity.end_time, format: :nice_date_and_time)
      %dt
        = t('activities.location')
      %dd
        = @activity.location
        %br
        %br
        %a#show-map= t('activity_form.location.show-map')

    .meeting-point-map#meeting-point-map
      = image_tag 'activities/meeting_points.jpg'